### PR TITLE
Feature/raw query runner

### PR DESCRIPTION
**Pull request by gurleensethi**
Functionality to run raw queries on the database.
Result from a `SELECT` query is displayed in `PaginatedDataTable`.

### CODE REVIEW

**Review by mcrovero — APPROVED** [review]

**Comment by mcrovero** [comment]
I think it's great! We could also add templates in the raw query page based on your tables and rows, what do you think?

**Review by ArtHoffmann — COMMENTED** [review]
good work!

**Comment by leen-nobbas** [comment]
@mcrovero Could you elaborate about the template thingy ?
@ArtHoffmann can this be merged if everything is ok.

**Comment by gurleensethi** [comment]
@mcrovero Could you elaborate about the template thingy ?
@ArtHoffmann can this be merged if everything is ok.

**Pull request merged**
